CREATE DATABASE pim_tool_project
GO

USE pim_tool_project
GO

-- Create EMPLOYEE table
CREATE TABLE [EMPLOYEE] (
    ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    VISA CHAR(3) NOT NULL,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    BIRTH_DATE DATE NOT NULL,
    [VERSION] INT NOT NULL
);
GO

-- Create GROUP table
CREATE TABLE [GROUP_TBL] (
    ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    GROUP_LEADER_ID BIGINT NOT NULL,
    [VERSION] INT NOT NULL
);
GO

-- Create PROJECT table
CREATE TABLE [PROJECT] (
    ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    GROUP_ID BIGINT NOT NULL,
    PROJECT_NUMBER INT UNIQUE NOT NULL,
    [NAME] VARCHAR(50) NOT NULL,
    CUSTOMER VARCHAR(50) NOT NULL,
    [STATUS] CHAR(3) NOT NULL,
    [START_DATE] DATE NOT NULL,
    END_DATE DATE,
    [VERSION] INT NOT NULL
);
GO

-- Create PROJECT_EMPLOYEE table
CREATE TABLE [PROJECT_EMPLOYEE] (
    PROJECT_ID BIGINT NOT NULL,
    EMPLOYEE_ID BIGINT NOT NULL,
    PRIMARY KEY (PROJECT_ID, EMPLOYEE_ID)
);
GO

-- Add Foreign Key for GROUP
ALTER TABLE [GROUP_TBL]
ADD CONSTRAINT FK_GROUP_EMPLOYEE
FOREIGN KEY (GROUP_LEADER_ID) REFERENCES EMPLOYEE(ID);
GO

-- Add Foreign Key for Project
ALTER TABLE PROJECT
ADD CONSTRAINT FK_PROJECT_GROUP
FOREIGN KEY (GROUP_ID) REFERENCES [GROUP_TBL](ID);
GO

-- Add Foreign Key for PROJECT_EMPLOYEE
ALTER TABLE PROJECT_EMPLOYEE
ADD CONSTRAINT FK_PROJECT_EMPLOYEE_PROJECT
FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT(ID);
GO

ALTER TABLE PROJECT_EMPLOYEE
ADD CONSTRAINT FK_PROJECT_EMPLOYEE_EMPLOYEE
FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(ID);
GO

---------------------------------------------------------------------------------
-- Add data for Employee
INSERT INTO EMPLOYEE (VISA, FIRST_NAME, LAST_NAME, BIRTH_DATE, [VERSION]) VALUES
('ABC', 'John', 'Doe', '1990-05-15', 1);
INSERT INTO EMPLOYEE (VISA, FIRST_NAME, LAST_NAME, BIRTH_DATE, [VERSION]) VALUES
('DEF', 'Jane', 'Smith', '1985-08-22', 1);
INSERT INTO EMPLOYEE (VISA, FIRST_NAME, LAST_NAME, BIRTH_DATE, [VERSION]) VALUES
('GHI', 'Robert', 'Johnson', '1992-03-10', 1);
INSERT INTO EMPLOYEE (VISA, FIRST_NAME, LAST_NAME, BIRTH_DATE, [VERSION]) VALUES
('JKL', 'Emily', 'Williams', '1988-11-28', 1);
INSERT INTO EMPLOYEE (VISA, FIRST_NAME, LAST_NAME, BIRTH_DATE, [VERSION]) VALUES
('MNO', 'William', 'Brown', '1995-07-04', 1);
INSERT INTO EMPLOYEE (VISA, FIRST_NAME, LAST_NAME, BIRTH_DATE, [VERSION]) VALUES
('PQR', 'Jessica', 'Miller', '1987-09-17', 1);
INSERT INTO EMPLOYEE (VISA, FIRST_NAME, LAST_NAME, BIRTH_DATE, [VERSION]) VALUES
('STU', 'Michael', 'Jones', '1993-02-05', 1);
INSERT INTO EMPLOYEE (VISA, FIRST_NAME, LAST_NAME, BIRTH_DATE, [VERSION]) VALUES
('VWX', 'Sophia', 'Taylor', '1990-06-20', 1);
INSERT INTO EMPLOYEE (VISA, FIRST_NAME, LAST_NAME, BIRTH_DATE, [VERSION]) VALUES
('YZA', 'Daniel', 'Anderson', '1986-12-12', 1);
INSERT INTO EMPLOYEE (VISA, FIRST_NAME, LAST_NAME, BIRTH_DATE, [VERSION]) VALUES
('BCD', 'Olivia', 'Wilson', '1991-04-30', 1);
INSERT INTO EMPLOYEE (VISA, FIRST_NAME, LAST_NAME, BIRTH_DATE, [VERSION]) VALUES
('EFG', 'Christopher', 'White', '1989-10-08', 1);
INSERT INTO EMPLOYEE (VISA, FIRST_NAME, LAST_NAME, BIRTH_DATE, [VERSION]) VALUES
('HIJ', 'Ava', 'Moore', '1994-01-25', 1);
INSERT INTO EMPLOYEE (VISA, FIRST_NAME, LAST_NAME, BIRTH_DATE, [VERSION]) VALUES
('KLM', 'Matthew', 'Smith', '1984-07-15', 1);
INSERT INTO EMPLOYEE (VISA, FIRST_NAME, LAST_NAME, BIRTH_DATE, [VERSION]) VALUES
('NOP', 'Emma', 'Brown', '1997-03-02', 1);
INSERT INTO EMPLOYEE (VISA, FIRST_NAME, LAST_NAME, BIRTH_DATE, [VERSION]) VALUES
('QRS', 'Jacob', 'Davis', '1983-09-12', 1);
INSERT INTO EMPLOYEE (VISA, FIRST_NAME, LAST_NAME, BIRTH_DATE, [VERSION]) VALUES
('TUV', 'Ella', 'Harris', '1996-05-18', 1);
INSERT INTO EMPLOYEE (VISA, FIRST_NAME, LAST_NAME, BIRTH_DATE, [VERSION]) VALUES
('WXY', 'Andrew', 'Clark', '1982-11-05', 1);
INSERT INTO EMPLOYEE (VISA, FIRST_NAME, LAST_NAME, BIRTH_DATE, [VERSION]) VALUES
('ZAB', 'Grace', 'Martinez', '1989-01-30', 1);
INSERT INTO EMPLOYEE (VISA, FIRST_NAME, LAST_NAME, BIRTH_DATE, [VERSION]) VALUES
('CDE', 'Logan', 'Jackson', '1998-08-22', 1);
INSERT INTO EMPLOYEE (VISA, FIRST_NAME, LAST_NAME, BIRTH_DATE, [VERSION]) VALUES
('FGH', 'Lily', 'Lee', '1981-04-11', 1);
INSERT INTO EMPLOYEE (VISA, FIRST_NAME, LAST_NAME, BIRTH_DATE, [VERSION]) VALUES
('IJK', 'David', 'Taylor', '1997-06-28', 1);
INSERT INTO EMPLOYEE (VISA, FIRST_NAME, LAST_NAME, BIRTH_DATE, [VERSION]) VALUES
('LMN', 'Chloe', 'Walker', '1980-12-25', 1);
INSERT INTO EMPLOYEE (VISA, FIRST_NAME, LAST_NAME, BIRTH_DATE, [VERSION]) VALUES
('OPQ', 'John', 'Young', '1996-02-14', 1);
INSERT INTO EMPLOYEE (VISA, FIRST_NAME, LAST_NAME, BIRTH_DATE, [VERSION]) VALUES
('RST', 'Madison', 'Ward', '1982-10-01', 1);
INSERT INTO EMPLOYEE (VISA, FIRST_NAME, LAST_NAME, BIRTH_DATE, [VERSION]) VALUES
('UVW', 'Christopher', 'Turner', '1993-07-08', 1);
INSERT INTO EMPLOYEE (VISA, FIRST_NAME, LAST_NAME, BIRTH_DATE, [VERSION]) VALUES
('XYZ', 'Isabella', 'Evans', '1985-05-03', 1);
INSERT INTO EMPLOYEE (VISA, FIRST_NAME, LAST_NAME, BIRTH_DATE, [VERSION]) VALUES
('ATN', 'Anh Thu', 'Nguyen Ba', '1985-05-03', 1);
INSERT INTO EMPLOYEE (VISA, FIRST_NAME, LAST_NAME, BIRTH_DATE, [VERSION]) VALUES
('MKN', 'Minh Kha', 'Nguyen', '1985-05-03', 1);
INSERT INTO EMPLOYEE (VISA, FIRST_NAME, LAST_NAME, BIRTH_DATE, [VERSION]) VALUES
('MQD', 'Minh Quang', 'Dang Vu', '1985-05-03', 1);
INSERT INTO EMPLOYEE (VISA, FIRST_NAME, LAST_NAME, BIRTH_DATE, [VERSION]) VALUES
('PNH', 'Hong Phong', 'Nguyen', '1985-05-03', 1);
GO

-- Add data for GROUP
INSERT INTO [GROUP_TBL] (GROUP_LEADER_ID, [VERSION]) 
VALUES
(28, 1),
(29, 1);
GO

-- Add data for Project
-- Group 1
INSERT INTO [PROJECT] (GROUP_ID, PROJECT_NUMBER, [NAME], CUSTOMER, [STATUS], [START_DATE], END_DATE, [VERSION]) VALUES
(1, 1, 'Innovative Solutions', 'Pierre Dupont', 'NEW', '2024-01-01', '2024-12-31', 1);
INSERT INTO [PROJECT] (GROUP_ID, PROJECT_NUMBER, [NAME], CUSTOMER, [STATUS], [START_DATE], END_DATE, [VERSION]) VALUES
(1, 3, 'Global Market Expansion', 'Marie Martel', 'PLA', '2024-02-01', '2024-11-30', 1);
INSERT INTO [PROJECT] (GROUP_ID, PROJECT_NUMBER, [NAME], CUSTOMER, [STATUS], [START_DATE], END_DATE, [VERSION]) VALUES
(1, 3116, 'Cybersecurity Enhancement Program', 'François Lefevre', 'INP', '2024-03-01', '2024-10-31', 1);
INSERT INTO [PROJECT] (GROUP_ID, PROJECT_NUMBER, [NAME], CUSTOMER, [STATUS], [START_DATE], END_DATE, [VERSION]) VALUES
(1, 3118, 'Sustainable Development Project', 'Élise Roussel', 'FIN', '2024-04-01', '2024-09-30', 1);
INSERT INTO [PROJECT] (GROUP_ID, PROJECT_NUMBER, [NAME], CUSTOMER, [STATUS], [START_DATE], END_DATE, [VERSION]) VALUES
(1, 5, 'Cloud Infrastructure Upgrade', 'Antoine Dubois', 'NEW', '2024-05-01', '2024-08-31', 1);
INSERT INTO [PROJECT] (GROUP_ID, PROJECT_NUMBER, [NAME], CUSTOMER, [STATUS], [START_DATE], END_DATE, [VERSION]) VALUES
(1, 6, 'Initiative de Transformation Numérique', 'Camille Lemoine', 'NEW', '2024-06-01', '2024-07-31', 1);
INSERT INTO [PROJECT] (GROUP_ID, PROJECT_NUMBER, [NAME], CUSTOMER, [STATUS], [START_DATE], END_DATE, [VERSION]) VALUES
(1, 7157, 'Exploration des Technologies Futures', 'Nicolas Girard', 'NEW', '2024-06-01', '2024-07-31', 1);
INSERT INTO [PROJECT] (GROUP_ID, PROJECT_NUMBER, [NAME], CUSTOMER, [STATUS], [START_DATE], END_DATE, [VERSION]) VALUES
(1, 7174, 'Solutions Innovantes', 'Emilie Berger', 'NEW', '2024-06-01', '2024-07-31', 1);
INSERT INTO [PROJECT] (GROUP_ID, PROJECT_NUMBER, [NAME], CUSTOMER, [STATUS], [START_DATE], END_DATE, [VERSION]) VALUES
(1, 7199, 'Expansion du Marché Mondial', 'Lucas Moreau', 'NEW', '2024-06-01', '2024-07-31', 1);
INSERT INTO [PROJECT] (GROUP_ID, PROJECT_NUMBER, [NAME], CUSTOMER, [STATUS], [START_DATE], END_DATE, [VERSION]) VALUES
(1, 8000, 'Projet de Développement Durable', 'Charlotte Lefevre', 'NEW', '2024-06-01', '2024-07-31', 1);
INSERT INTO [PROJECT] (GROUP_ID, PROJECT_NUMBER, [NAME], CUSTOMER, [STATUS], [START_DATE], END_DATE, [VERSION]) VALUES
(1, 8005, 'Amélioration de l''Expérience Client', 'Jules Roux', 'NEW', '2024-06-01', '2024-07-31', 1);
INSERT INTO [PROJECT] (GROUP_ID, PROJECT_NUMBER, [NAME], CUSTOMER, [STATUS], [START_DATE], END_DATE, [VERSION]) VALUES
(1, 8008, 'Développement de Partenariats Stratégiques', 'Emma Leroux', 'NEW', '2024-06-01', '2024-07-31', 1);
INSERT INTO [PROJECT] (GROUP_ID, PROJECT_NUMBER, [NAME], CUSTOMER, [STATUS], [START_DATE], END_DATE, [VERSION]) VALUES
(1, 9002, 'Mise en Œuvre de la Gestion de Projet Agile', 'Louis Petit', 'NEW', '2024-06-01', '2024-07-31', 1);
INSERT INTO [PROJECT] (GROUP_ID, PROJECT_NUMBER, [NAME], CUSTOMER, [STATUS], [START_DATE], END_DATE, [VERSION]) VALUES
(1, 9005, 'Optimisation de l''Analyse de Données', 'Chloé Bonnet', 'NEW', '2024-06-01', '2024-07-31', 1);
INSERT INTO [PROJECT] (GROUP_ID, PROJECT_NUMBER, [NAME], CUSTOMER, [STATUS], [START_DATE], END_DATE, [VERSION]) VALUES
(1, 10000, 'Programme d''Amélioration de la Cybersécurité', 'Mathieu Lefevre', 'NEW', '2024-06-01', '2024-07-31', 1);
GO

-- Group 2
INSERT INTO [PROJECT] (GROUP_ID, PROJECT_NUMBER, [NAME], CUSTOMER, [STATUS], [START_DATE], END_DATE, [VERSION]) VALUES
(2, 20001, 'Service Improvement Project', 'Jean Dupont', 'NEW', '2024-02-17', '2025-01-31', 1);
INSERT INTO [PROJECT] (GROUP_ID, PROJECT_NUMBER, [NAME], CUSTOMER, [STATUS], [START_DATE], END_DATE, [VERSION]) VALUES
(2, 20002, 'Innovative Platform Development', 'Marie Martin', 'PLA', '2024-02-17', '2025-01-31', 1);
INSERT INTO [PROJECT] (GROUP_ID, PROJECT_NUMBER, [NAME], CUSTOMER, [STATUS], [START_DATE], END_DATE, [VERSION]) VALUES
(2, 20003, 'New Technologies Integration Program', 'François Lefevre', 'INP', '2024-02-17', '2025-01-31', 1);
INSERT INTO [PROJECT] (GROUP_ID, PROJECT_NUMBER, [NAME], CUSTOMER, [STATUS], [START_DATE], END_DATE, [VERSION]) VALUES
(2, 20004, 'Sustainable Finance Project', 'Élise Roussel', 'FIN', '2024-02-17', '2025-01-31', 1);
INSERT INTO [PROJECT] (GROUP_ID, PROJECT_NUMBER, [NAME], CUSTOMER, [STATUS], [START_DATE], END_DATE, [VERSION]) VALUES
(2, 20005, 'Cybersecurity Innovation in Domain', 'Antoine Dubois', 'NEW', '2024-02-17', '2025-01-31', 1);
INSERT INTO [PROJECT] (GROUP_ID, PROJECT_NUMBER, [NAME], CUSTOMER, [STATUS], [START_DATE], END_DATE, [VERSION]) VALUES
(2, 20006, 'Digital Transformation Project', 'Camille Lemoine', 'PLA', '2024-02-17', '2025-01-31', 1);
INSERT INTO [PROJECT] (GROUP_ID, PROJECT_NUMBER, [NAME], CUSTOMER, [STATUS], [START_DATE], END_DATE, [VERSION]) VALUES
(2, 20007, 'Sustainable Development and Social Responsibility', 'Nicolas Girard', 'INP', '2024-02-17', '2025-01-31', 1);
INSERT INTO [PROJECT] (GROUP_ID, PROJECT_NUMBER, [NAME], CUSTOMER, [STATUS], [START_DATE], END_DATE, [VERSION]) VALUES
(2, 20008, 'Optimization of Financial Processes', 'Emilie Berger', 'FIN', '2024-02-17', '2025-01-31', 1);
INSERT INTO [PROJECT] (GROUP_ID, PROJECT_NUMBER, [NAME], CUSTOMER, [STATUS], [START_DATE], END_DATE, [VERSION]) VALUES
(2, 20009, 'Data Security Project', 'Lucas Moreau', 'NEW', '2024-02-17', '2025-01-31', 1);
INSERT INTO [PROJECT] (GROUP_ID, PROJECT_NUMBER, [NAME], CUSTOMER, [STATUS], [START_DATE], END_DATE, [VERSION]) VALUES
(2, 20010, 'Innovation in the Energy Sector', 'Charlotte Lefevre', 'PLA', '2024-02-17', '2025-01-31', 1);
INSERT INTO [PROJECT] (GROUP_ID, PROJECT_NUMBER, [NAME], CUSTOMER, [STATUS], [START_DATE], END_DATE, [VERSION]) VALUES
(2, 20011, 'Supply Chain Management Program', 'Jules Roux', 'INP', '2024-02-17', '2025-01-31', 1);
INSERT INTO [PROJECT] (GROUP_ID, PROJECT_NUMBER, [NAME], CUSTOMER, [STATUS], [START_DATE], END_DATE, [VERSION]) VALUES
(2, 20012, 'Investment in Infrastructure Project', 'Emma Leroux', 'FIN', '2024-02-17', '2025-01-31', 1);
INSERT INTO [PROJECT] (GROUP_ID, PROJECT_NUMBER, [NAME], CUSTOMER, [STATUS], [START_DATE], END_DATE, [VERSION]) VALUES
(2, 20013, 'Innovation in the Healthcare Sector', 'Louis Petit', 'NEW', '2024-02-17', '2025-01-31', 1);
INSERT INTO [PROJECT] (GROUP_ID, PROJECT_NUMBER, [NAME], CUSTOMER, [STATUS], [START_DATE], END_DATE, [VERSION]) VALUES
(2, 20014, 'Human Resources Development Project', 'Chloé Bonnet', 'PLA', '2024-02-17', '2025-01-31', 1);
INSERT INTO [PROJECT] (GROUP_ID, PROJECT_NUMBER, [NAME], CUSTOMER, [STATUS], [START_DATE], END_DATE, [VERSION]) VALUES
(2, 20015, 'Optimization of Financial Operations', 'Mathieu Lefevre', 'INP', '2024-02-17', '2025-01-31', 1);
GO

-- Add data for Project Employee
INSERT INTO PROJECT_EMPLOYEE (PROJECT_ID, EMPLOYEE_ID)
VALUES
-- Group 1 - Project 1
(1, 1), (1, 2), (1, 3),
-- Group 1 - Project 2
(2, 4), (2, 5), (2, 6),
-- Group 1 - Project 3
(3, 7), (3, 8), (3, 9),
-- Group 1 - Project 4
(4, 10), (4, 11), (4, 12),
-- Group 1 - Project 5
(5, 13), (5, 14), (5, 15),
-- Group 2 - Project 6
(6, 16), (6, 17), (6, 18),
-- Group 2 - Project 7
(7, 19), (7, 20), (7, 21),
-- Group 2 - Project 8
(8, 22), (8, 23), (8, 24),
-- Group 2 - Project 9
(9, 25), (9, 26), (9, 27),
-- Group 2 - Project 10
(10, 28), (10, 29), (10, 30);
GO